### For the Practice excercise for Lession 06: 

In this exercise we will examine the outputs from simple untrained LSTM and GRU networks, in order to better understand the Keras API.

There are four parts, and 12 short questions to answer as you run the code below:

1. LSTM: run with return_sequences=False
2. LSTM: run with return_sequences=True
3. GRU: run with return_sequences=False
4. GRU: run with return_sequences=True

In [ ]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np

timesteps = 8
num_features = 2
num_nodes = 3

#Create some random data
data = np.random.randn(1, timesteps, num_features)
print(data)

[[[-1.28875918  0.35352327]
  [-0.91360787  1.03423392]
  [ 0.97712755  1.07813044]
  [-0.84268605  0.81410969]
  [-0.72858672  0.66930141]
  [-1.0776233  -1.19782537]
  [ 0.32717254 -0.34321601]
  [-0.42937633 -0.19439394]]]


In [ ]:
data.shape

(1, 8, 2)

Q1: What do the dimensions of the data represent? E.g., what do the 1st dimension, the 2nd, and the 3rd represent here?

1st dimension: batch size (=1)
2nd dimension: timesteps (=8)
3rd dimension: number of features (=2) 

In [ ]:
#LSTM: run with return_sequence = False

inputs = Input(shape=(timesteps, num_features))
rnn = LSTM (num_nodes, return_state = True)
x = rnn(inputs)

model = Model(inputs=inputs, outputs = x)

output, h, c = model.predict(data)

print("output:", output)
print("h:", h)
print("c:", c)

output: [[-0.25732717 -0.12740867  0.14300866]]
h: [[-0.25732717 -0.12740867  0.14300866]]
c: [[-0.52285177 -0.2680984   0.2633277 ]]


Q2: What do these "predict" return values (output, h, and c) represent? Describe what they mean.

Q3: What are the dimensions of output, h, and c?




In [ ]:
output.shape

(1, 3)

In [ ]:
h.shape

(1, 3)

In [ ]:
c.shape

(1, 3)

Q4: Is there any duplication among the values of (output, h, c)? If so, explain.

Q5: Change the LSTM to use "return_state=False" and modify the code accordingly to avoid errors. What does the LSTM return now?

In [ ]:
#LSTM: run with return_state = False

inputs = Input(shape=(timesteps, num_features))
rnn = LSTM (num_nodes, return_state = False)
x = rnn(inputs)

model = Model(inputs=inputs, outputs = x)

output = model.predict(data)

print("output:", output)


output: [[-0.15197638  0.01377018 -0.07396807]]


Run with return_sequence = True

In [ ]:
#LSTM: run with return_sequence = False

inputs = Input(shape=(timesteps, num_features))
rnn = LSTM (num_nodes, return_sequences= True, return_state = True)
x = rnn(inputs)

model = Model(inputs=inputs, outputs = x)

output, h, c = model.predict(data)

print("output:", output)
print("h:", h)
print("c:", c)

output: [[[-0.05612301 -0.06896988 -0.18579502]
  [-0.1875263  -0.06667361 -0.32710493]
  [-0.17990069  0.13244492 -0.1955806 ]
  [-0.29050726  0.03078281 -0.41637388]
  [-0.28513885  0.01093456 -0.4316702 ]
  [-0.09143886 -0.0999801  -0.36889783]
  [-0.02488659  0.03234047 -0.14718549]
  [-0.01412397 -0.02643303 -0.12061352]]]
h: [[-0.01412397 -0.02643303 -0.12061352]]
c: [[-0.02710348 -0.05504766 -0.21965176]]


Q6: Now, what are the dimensions of output, h, and c?

Q7: What does the output variable represent now? Explain the dimensions of the returned matrix (e.g., what does the 1st dimension represent? What does the 2nd represent? The 3rd? etc.)

In [ ]:
output.shape

(1, 8, 3)

GRU

In [ ]:
inputs = Input(shape=(timesteps, num_features))

rnn = GRU(num_nodes, return_state=True)

x = rnn(inputs)

 

model = Model(inputs=inputs, outputs=x)

output, h = model.predict(data)

print("o:", output)

print("h:", h)

o: [[-0.29243028  0.41559392 -0.12007254]]
h: [[-0.29243028  0.41559392 -0.12007254]]


Q8: What happened to the variable "c"? Why does the GRU only return a tuple of 2 values as opposed to 3?

Q9: What are the dimension of output and h?

In [ ]:
output.shape

(1, 3)

In [ ]:
h.shape

(1, 3)

Q10: Is there any duplication between the values of output and h? If so, explain.

Run with return_sequences=True

In [ ]:
inputs = Input(shape=(timesteps, num_features))

rnn = GRU(num_nodes, return_sequences=True, return_state=True)

x = rnn(inputs)

 

model = Model(inputs=inputs, outputs=x)

output, h = model.predict(data)

print("o:", output)

print("h:", h)

o: [[[ 0.0309521   0.36112666 -0.2695216 ]
  [-0.201059    0.5110463  -0.52815104]
  [-0.40577215  0.1851165  -0.12411187]
  [-0.41022527  0.36255985 -0.43215796]
  [-0.35124218  0.48350626 -0.5538353 ]
  [ 0.3398422   0.6222069  -0.47628465]
  [ 0.3386014   0.24319556 -0.12537238]
  [ 0.35191953  0.3164274  -0.1449812 ]]]
h: [[ 0.35191953  0.3164274  -0.1449812 ]]


Q11: Now, what are the dimensions of output and h?

Q12: Is there any duplication within the values of output and h? If so, explain. 